name: django-remote-resources
version: 0.3.0-a3
description: Sync remote API resources to Django models

repo_url: https://github.com/kaoslabsinc/django-remote-resources
project_url: https://github.com/kaoslabsinc/django-remote-resources
keywords: django, api, resource, sync, remote, remote resource, etl, remote object
